#pragma once
//Screen dimensions
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MOVEMENT_SPEED 150.0f
#define GRAVITY_STRENGTH 260.0f
#define JUMP_FORCE_DECREMENT 400.0f
#define INITIAL_JUMP_FORCE 600.0f
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define SHAKE_DURATION 0.25f